services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    configs:
      - source: rabbitmq-plugins
        target: /etc/rabbitmq/enabled_plugins
    volumes:
      - ./data/rabbitmq-lib:/var/lib/rabbitmq/
      - ./data/rabbitmq-log:/var/log/rabbitmq
    healthcheck: # Optional: waits for RabbitMQ to be healthy
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 5s
      timeout: 10s
      retries: 5
  rabbitmqkata:
    image: rabbitmqkata
    build:
      context: .
      dockerfile: RabbitMQKata/Dockerfile
    env_file:
      - .env
    depends_on:
      rabbitmq: # Ensures RabbitMQ is started before publisher
        condition: service_healthy # Waits for healthcheck to pass
        
configs:
  rabbitmq-plugins:
    content: "[rabbitmq_management]."

volumes:
  rabbitmq-lib:
    driver: local
  rabbitmq-log:
    driver: local
